Este netbook realizara un Análisis Exploratorio de Datos (EDA) enfocado en la caracterización estructural del dataset, la evolucion y la identificación de comportamientos relevantes para guiar procesos posteriores de preprocesamiento y construcción de modelos.

In [4]:
import pandas as pd
import numpy as np
import os

In [9]:
ruta_archivo = "../data/raw/base_homicidios.csv"

try:
    if not os.path.exists(ruta_archivo):
        raise FileNotFoundError(f"No se encontro el archivo en {os.path.abspath(ruta_archivo)}")

    df = pd.read_csv(ruta_archivo)
    print(f"Carga exitosa: {df.shape[0]} filas y {df.shape[1]} columnas cargadas.")

except Exception as e:
    print(f"Error critico en la carga: {e}")

Carga exitosa: 22092 filas y 6 columnas cargadas.

## Vista general del Dataframe

In [10]:
df.head(5)

  iso_code      country  year   sex age_group  homicide_rate
0      AFG  Afghanistan  2009  both       ALL       4.059550
1      AFG  Afghanistan  2010  both       ALL       3.475452
2      AFG  Afghanistan  2011  both       ALL       4.194535
3      AFG  Afghanistan  2012  both       ALL       6.374339
4      AFG  Afghanistan  2015  both       ALL       9.952186

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22092 entries, 0 to 22091
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   iso_code       22092 non-null  object
 1   country        22092 non-null  object
 2   year           22092 non-null  int64
 3   sex            22092 non-null  object
 4   age_group      22092 non-null  object
 5   homicide_rate  22092 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 1.0+ MB

In [13]:
df.describe()

               year  homicide_rate
count  22092.000000   22092.000000
mean    2013.046306       8.586870
std        7.944182      21.311232
min     1990.000000       0.000000
25%     2009.000000       0.624042
50%     2015.000000       1.749959
75%     2019.000000       6.123606
max     2023.000000     373.710962

In [16]:
df.columns

Index(['iso_code', 'country', 'year', 'sex', 'age_group', 'homicide_rate'], dtype='object')

In [ ]:
df.dtypes